### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by User888888** [aderusha/Get-PrusaFwDevEnv#1]
Hi Aderusha,

Your script is really helpful for windows users, but I am getting an error when I try to compile the "Configuration_prusa.h"

I have attached the screen shot of the error which I am getting during compilation

Thanks

![screenshot_4](https://cloud.githubusercontent.com/assets/27830040/25251796/236825ee-2638-11e7-93ac-86b978f67907.jpg)

**Comment by User888888** [comment]
Below is the complete ERROR message which I am getting during compilation - 

Arduino: 1.6.8 (Windows 10), Board: "RAMBo"

WARNING: Category '' in library Wire is not valid. Setting to 'Uncategorized'
Warning: platform.txt from core 'Marlin AVR Boards' contains deprecated recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{build.path}/{archive_file}" "{object_file}", automatically converted to recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{archive_file_path}" "{object_file}". Consider upgrading this core.
ultralcd.cpp:117: error: redefinition of 'bool long_press_active'

 bool long_press_active = false;

      ^

ultralcd.cpp:112: error: 'bool long_press_active' previously defined here

 bool long_press_active = false;

      ^

ultralcd.cpp:118: error: redefinition of 'long int long_press_timer'

 long long_press_timer = millis();

      ^

ultralcd.cpp:113: error: 'long int long_press_timer' previously declared here

 long long_press_timer = millis();

      ^

ultralcd.cpp:119: error: redefinition of 'bool button_pressed'

 bool button_pressed = false;

      ^

ultralcd.cpp:115: error: 'bool button_pressed' previously defined here

 bool button_pressed = false;

      ^

exit status 1
redefinition of 'bool long_press_active'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by aderusha** [comment]
That specific bug was due to the Prusa firmware codebase at the time which you ran the script.  The error has apparently been fixed with the latest code, so if you run it again everything should work as expected.

This can't really be avoided if you're pulling the latest code, if Prusa breaks the codebase it's broken until they fix it.
